### ISSUE TITLE
Go over launch checklist

### ISSUE THREAD

**Issue by llorca** [spolu/dazzle#13]
Credit: http://mrgan.com/check/

### Writing
- [ ] Write the announcement tweet. Silly? It’s like writing a tagline for an ad campaign! It’s huge!
- [ ] Write the friends-and-family announcement email. This one can be a bit more “you”. Offer individual promo codes, why not.

### Website
- [ ] Triple-check all links. You’ve probably used placeholders for the app url and such. Time to make it all real.
- [x] If you’re using caching, warm the caches. If you’re running on Heroku, scale up your dynos. In general, prepare your website for (one hopes) heavy traffic.
- [x] Add analytics. Me, I always forget this until two weeks after a launch.

### Social
- [x] Add [Twitter Card](https://dev.twitter.com/cards/overview) and [Open Graph](http://ogp.me/) metadata to your website.
- [ ] Pin your announcement tweet. It’s what people will see when they check your profile because you have a 🔥 avatar.
- [x] Make a promo image. This is totally optional, but a big, eye-catching graphic will go well with your tweet or Facebook post or whatever. I’m sorry.

### Apps
- [x] Double-check the app title, description, and keywords. After that, double-check the app title, description, and keywords.
- [ ] Generate an affiliate link and use it whenever you link to the app. Oh yeah baby, extra pennies!
- [ ] Generate promo codes so you can send them out tout suite.
